Temporal grouper index rjsf
wildlife-dynamics/ecoscope-workflows pull request #461
Opened 2024-11-20 22:03 UTC by atmorling

closes #446

2024-11-21 06:05 UTC, cisaacstern reviewed
Looks like Field(json_schema_extra=...) is a good way into this.

I made some implementation/stylistic suggests below.

Before we merge this we should also figure out what specific subset of these directives we want to support, and for those, use the better text (plus example) from https://strftime.org/.

2024-11-21 06:05 UTC, cisaacstern commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
> +}
enum/enunNames is apparently deprecated in RJSF, see https://github.com/wildlife-dynamics/ecoscope-workflows/issues/151

Which, if memory serves, is why we went with the [oneOf implementation like this](https://github.com/wildlife-dynamics/ecoscope-workflows/blob/2989e5b247ad1a6ca58d74a6477d8a19026c163a/src/ecoscope-workflows-core/ecoscope_workflows_core/jsonschema.py#L46-L55)

For consistency, I would suggest we leverage that existing definition. Combining this with the idea above of iterating on keys/values, I would suggest we do the following (also, with a snake case variable name since this is an instance of oneOf):

```suggestion
from ecoscope_workflows_core.jsonschema import oneOf

temporal_index_json_schema_extra = oneOf(
    const=[k for k in strftime_directives.keys()],
    title=[v for v in strftime_directives.values()],
).model_dump()
```

2024-11-21 06:05 UTC, cisaacstern commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
> +        Field(json_schema_extra=TemporalIndexJsonSchemaExtra),
```suggestion
        Field(json_schema_extra=temporal_index_json_schema_extra),
```

2024-11-21 06:07 UTC, cisaacstern commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
> +}
I'm not certain if the above code runs, but I imagine if it doesn't, it's quite close to being able to.

2024-11-21 06:09 UTC, cisaacstern commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
> +}
We may need to use the key `"oneOf"` as we do for the dashboard filters here

https://github.com/wildlife-dynamics/ecoscope-workflows/blob/2989e5b247ad1a6ca58d74a6477d8a19026c163a/src/ecoscope-workflows-core/ecoscope_workflows_core/jsonschema.py#L69

so maybe something like 

```python
temporal_index_json_schema_extra = {
    "oneOf": oneOf(
        const=[k for k in strftime_directives.keys()],
        title=[v for v in strftime_directives.values()],
    ).model_dump()
}
```

2024-11-21 09:09 UTC, cisaacstern commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
> +    {"%A": "Locale's full weekday name."},
you probably realized this but the ci is failing bc this is list of dicts rather than just a dict.

2024-11-21 09:22 UTC, cisaacstern commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
> +).model_dump()
```suggestion
temporal_index_json_schema_extra = {
    "oneOf": [
         oneOf(const=k, title=v).model_dump()
         for k, v in strftime_directives
    ]
}
```

oops i lead you astray with this recommendation, it should be something like this

2024-11-21 09:24 UTC, atmorling commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
> +).model_dump()
no stress! on it :smile:

2024-11-21 09:26 UTC, atmorling commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
> +).model_dump()
Local recompile definitely seems quicker for iterating on things like this

2024-11-21 09:39 UTC, cisaacstern commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
> +).model_dump()
fair!

2024-11-21 10:53 UTC, atmorling reviewed
This works, but introduce some potentially confusing behaviour in the RJSF such that if a user does the following:

- Selects Temporal Grouper from the Grouper drop-down
- Selects a Temporal Index 
- Switches the Grouper drop-down to a Value Grouper
The "value" of the selected Temporal Index (ie "%B") will be visible in the free text field for Value Grouper.

This is because `index_name` is shared between the two Grouper options, AND because the `IndexName` type ([here](https://github.com/wildlife-dynamics/ecoscope-workflows/blob/f9d5086e5e04d6555f68b49395e743fef6dd5f6f/src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py#L71-L72)) is just any `str`

I don't think this is a dealbreaker but it definitely highlights the need for a similar "shift letf" lift on Value Groupers

2024-11-21 10:53 UTC, atmorling commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
> +        AfterValidator(validate_temporal_index),
This is necessary because the `enum` generated by `Literal[TemporalIndexSelector]` creates conflicts with `oneOf`

2024-11-21 19:56 UTC, cisaacstern commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
> +        AfterValidator(validate_temporal_index),
Can you give an example?

2024-11-21 19:57 UTC, cisaacstern commented
> Then the "value" of the selected Temporal Index (ie "%B") will be visible in the free text field for Value Grouper.
> This is because index_name is shared between the two Grouper options

I think if both elements of the union type have the same args, pydantic may struggle to discriminate accurately between them on parse? Perhaps the best solution is just to choose different names for these args?

2024-11-21 21:11 UTC, atmorling commented
> > Then the "value" of the selected Temporal Index (ie "%B") will be visible in the free text field for Value Grouper.
> > This is because index_name is shared between the two Grouper options
> 
> I think if both elements of the union type have the same args, pydantic may struggle to discriminate accurately between them on parse? Perhaps the best solution is just to choose different names for these args?

:eyes: Nice intuition! That's exactly why the last CI run failed.

2024-11-21 21:32 UTC, atmorling commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
> +        AfterValidator(validate_temporal_index),
So using this 
```python
    index_name: Annotated[
        Literal[TemporalIndexSelector],
        Field(json_schema_extra=temporal_index_json_schema_extra),
    ]
```
Generates [this](https://gist.github.com/atmorling/4106952062bb1288fb8c6d1f73373a8a) with `enum` and `oneOf`

Playing around with it some more just now, and knowing what I didn't realise at the time, which is that Pydantic struggles to discriminate, I think this is also true for the form renderer and is what is happening here. I'm gonna fix the arg name and then revert this as a test.

2024-11-21 21:45 UTC, atmorling commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
> +        AfterValidator(validate_temporal_index),
Realised I could just test that in RJSF.... that does seem to hold true

2024-11-21 23:02 UTC, atmorling commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
> +        AfterValidator(validate_temporal_index),
In the above example, the Literal is from the display values. This is obviously fine in RJSF land but means that if one is ever defining TemporalGroupers in Python, one would have to provide "Month (September)" rather than "%B"

Unfortunately building the Literal from the directives causes issues with RJSF because the list of values in `enum` is now different to the list of `title`'s in `oneOf` ie:
```json
"index_name": {
  "enum": [
    "%a",
    "$A",
    "%b"
  ],
  "oneOf": [
    {
      "const": "%a",
      "title": "Locale's abbreviated weekday name."
    },
    {
      "const": "%A",
      "title": "Locale's full weekday name."
    },
    {
      "const": "%b",
      "title": "Locale's abbreviated month name."
    },
  ],
  "title": "Index Name",
  "type": "string"
}

```

2024-11-21 23:14 UTC, cisaacstern commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
> +        AfterValidator(validate_temporal_index),
This feels to me like we shouldn't be "doubling up" on this definition... like maybe we want to use WithJsonSchema so we don't need to deal with the enum at all?

2024-11-22 07:57 UTC, atmorling commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
> +        AfterValidator(validate_temporal_index),
I think you're right, there's also not that much to the generated schema so "overriding" it doesn't seem too brittle

2024-11-22 16:08 UTC, cisaacstern commented on src/ecoscope-workflows-core/ecoscope_workflows_core/jsonschema.py
> +        return self.const.__hash__()
Maybe something like

```suggestion
    def __hash__(self) -> int:
        return hash(("oneOf", self.const, self.title))
```

?

2024-11-22 16:14 UTC, atmorling commented on src/ecoscope-workflows-core/ecoscope_workflows_core/jsonschema.py
> +        return self.const.__hash__()
Sure!

2024-11-22 17:13 UTC, cisaacstern commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
> +    "%H": "Hour (24-hour clock) as number (Example: 22)",
```suggestion
    "%Y": "Year (example: 2024)",
    "%B": "Month (example: September)",
    "%j": "Day of the year as a number (example: 365)",
    "%d": "Day of the month as a number (example: 31)",
    "%A": "Day of the week (example: Sunday)",
    "%H": "Hour (24-hour clock) as number (example: 22)",
```

2024-11-22 18:05 UTC, cisaacstern commented
Let's make sure we are still getting a good display name on the frontend

https://github.com/wildlife-dynamics/ecoscope-workflows/blob/c0195cc246f3a7fa4d0a1015dd44fa4dee5b469b/src/ecoscope-workflows-core/ecoscope_workflows_core/tasks/results/_dashboard.py#L154

2024-11-22 18:07 UTC, cisaacstern commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
>      ] = None
Let's make this a property

```python
@property
def display_name(self):
    return strftime_directives[self.index_name].split("(")[0].strip()

```

2024-11-22 18:11 UTC, cisaacstern commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
>      ] = None
Per Alex suggestion, let's make the directives frozen dataclasses! 🎉

2024-11-22 20:13 UTC, cisaacstern commented on examples/events/test-cases.yaml
> +            display_name: "Month"
@atmorling I would expect this to reflect 1:1 what the RJSF input needs to be.

```suggestion
        - temporal_index:
            selector_title: "Month (example: September)"
```
?

2024-11-22 20:14 UTC, cisaacstern commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
> +    display_name: str = "Hour"
Lowercase `e` for example would be my preference, sry to be picky 🫣

2024-11-22 20:15 UTC, cisaacstern commented on examples/patrols/test-cases.yaml
> +            display_name: "Month"
```suggestion
        - temporal_index:
            selector_title: "Month (Example: September)"
```
?

2024-11-22 20:15 UTC, cisaacstern commented on examples/subject-tracking/test-cases.yaml
> +            display_name: "Month"
```suggestion
        - temporal_index:
            selector_title: "Month (Example: September)"
```

?

2024-11-22 20:15 UTC, atmorling commented on src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py
> +    display_name: str = "Hour"
Skill issue on my part. I actually fixed this and then clearly blew it away

2024-11-22 20:16 UTC, cisaacstern reviewed
@atmorling the gist of the test-cases suggestions I've made is that, if that yaml doesn't reflect 1:1 what the RJSF inputs need to be, then we're doing something wrong. That's kinda the idea behind test-cases.yaml: it shows us an example of what we expect the user to need to input.

2024-11-22 20:19 UTC, atmorling commented
> @atmorling the gist of the test-cases suggestions I've made is that, if that test-cases.yaml doesn't reflect 1:1 what the RJSF inputs need to be, then we're doing something wrong. That's kinda the idea behind test-cases.yaml: it shows us an example of what we expect the user to need to input.

Fair - was more basing it off what the returned form data would look like, which is distinct from the user input

2024-11-22 20:24 UTC, cisaacstern commented
> Fair - was more basing it off what the returned form data would look like, which is distinct from the user input

Will this even be what the formadata looks like, though? I think you mean the _parsed_ result of the `FormData` object, which is different from the returned form data.

2024-11-22 20:25 UTC, atmorling commented
Some of the mypy failures on teh latest are interesting: https://github.com/wildlife-dynamics/ecoscope-workflows/actions/runs/11979488364/job/33401775360?pr=461

The `_dashboard` failures should have reared it's head as soon as we changed `index_name` to `temporal_index` but has only surfaced now..

2024-11-22 20:27 UTC, cisaacstern commented
> The _dashboard failures should have reared it's head as soon as we changed index_name to temporal_index but has only surfaced now..

At one point I think the TemporalGrouper had `index_name` as a `@property` which seems to be gone now, and is why these errors are occuring?

2024-11-22 20:29 UTC, atmorling commented
Yep :facep

2024-11-22 21:34 UTC, cisaacstern commented on examples/events/test-cases.yaml
> +            selector_title: "Month (Example: September)"
I am on mobile at the moment so hard to make a more specific suggestion. I can take a closer look when I'm back at the desk in a bit, if useful.

2024-11-22 22:26 UTC, atmorling commented on examples/events/test-cases.yaml
> +            selector_title: "Month (Example: September)"
The union type might be the problem, I've tried a few different cuts of yaml

2024-11-22 23:04 UTC, atmorling commented on examples/events/test-cases.yaml
> +            selector_title: "Month (Example: September)"
Looks like a mismatch between the Param model and the task input, 

https://github.com/wildlife-dynamics/ecoscope-workflows/blob/9a852ed820437d43275c880b9c7e49af997fe8bd/examples/events/ecoscope-workflows-events-workflow/ecoscope_workflows_events_workflow/params.py#L70-L71

Params expects a string but our task is a Union Type of all the frozen dataclasses

https://github.com/wildlife-dynamics/ecoscope-workflows/blob/9a852ed820437d43275c880b9c7e49af997fe8bd/src/ecoscope-workflows-core/ecoscope_workflows_core/indexes.py#L91-L95

2024-11-25 14:45 UTC, davidovichmarcos approved these changes

2024-11-25 16:18 UTC, cisaacstern reviewed
So close!

Two comments below, one re: validation, and the other is because the Params should reflect what the frontend sends.

2024-11-25 16:18 UTC, cisaacstern commented on examples/events/test-cases.yaml
> +            display_name: "Year"
A few comments:

- I think validation on the TemporalGrouper should not allow this combination? (`%B` and `Year...` are not compatible?)
- With the change to `type: "object"` below, would this also work?

```diff
-           directive: "%B"
            selector_title:  "Year (example: 2024)"
-           display_name: "Year"
```

I note that the variant of this above had capital `Example`, which may have been part of the problem.

2024-11-26 00:10 UTC, cisaacstern requested changes
Tests are now passing but rjsf is not looking like it's rendering correctly in the playground, going to take a look at that now. Adding this "request changes" review to flag that this needs a further look before merge, despite passing tests.

2024-11-26 05:50 UTC, cisaacstern approved these changes
RJSF now works with latest changes.

2024-11-26 07:57 UTC, merged