Create the simplest version of a patrol workflow
wildlife-dynamics/ecoscope-workflows pull request #80
Opened 2024-07-17 06:43 UTC by Yun-Wu

- **first try to create patrol workflow**
- **fix io issue**
- **fix param for ecomap**
- **fix unittest**

2024-07-17 06:53 UTC, Yun-Wu commented
@cisaacstern `EarthRangerClientProtocol` is causing me validation errors as `EarthRangerIO != EarthRangerClientProtocol`. I had to remove it in the task and use `EarthRangerIO` directly. If I understand correctly, it is used as the interface between the data connection and the actual client. I removed it and it works fine. Could you please take a look at my fix and see if it makes sense to you?

2024-07-19 04:13 UTC, cisaacstern requested changes
Hi @Yun-Wu apologies for the delay on this. 

> EarthRangerClientProtocol is causing me validation errors as EarthRangerIO != EarthRangerClientProtocol. I had to remove it in the task and use EarthRangerIO directly.

Sorry to hear that this was not working, clearly I/we have some work to do regarding documentation and/or developer experience here.

I am not comfortable with your fix here, however, as it introduces a "compile time" dependency on `ecoscope` core, which AFAICT we do not otherwise have.

My intention in using the Protocol as a stand-in for the actual EarthRangerIO object was to prevent taking this compile-time dependency on `ecoscope` core, and defer `ecoscope` core to being a runtime dependency only.

For an example of why this might matter, if/when we eventually run a microservice that compiles custom workflows, with `ecoscope` core imported at the module top level, we then require `ecoscope` (and, in turn, any of its dependencies) to be available to the compiler container. By using the Protocol as a stand-in at the module/outer layer, as I'm hoping we can do here, we avoid that dependency, which IMHO is beneficial. (Among other things, it means workflows compilation is only loosely and not tightly coupled to `ecosope` core dependency changes.)

Does that goal make sense?

If you have time sometime after one of the next few standups in the next few days, I'm happy to sync on debugging this. If you prefer, I could also give it a shot myself and then get back to you with any conclusions.

2024-07-19 05:35 UTC, Yun-Wu commented
@cisaacstern sure. Created this ticket to track the fix and assigned to you: https://github.com/wildlife-dynamics/ecoscope-workflows/issues/84

2024-07-19 22:43 UTC, cisaacstern reviewed
Here's a quick targeted review re: persisiting results. I've just opened #89 (which closes #81). Instead of handling persistence of results in the ecomap/plot tasks, we can use that task to do so.

Lmk if that seems like it can work, or if you have any concerns. 🙏

2024-07-19 22:43 UTC, cisaacstern commented on ecoscope_workflows/tasks/results/_ecomap.py
> +    return return_result
Rather than saving the HTML here, let's use #89 (or whatever that becomes post-review) to persist the text as part of the workflow definition.

2024-07-19 22:43 UTC, cisaacstern commented on ecoscope_workflows/tasks/results/_ecoplot.py
> +        )
Same comment as above re: using #89

2024-07-19 22:43 UTC, cisaacstern commented on examples/compilation-specs/patrol_workflow.yaml
> +    geodataframe: relocations_to_trajectory
```suggestion
  draw_ecomap:
    geodataframe: relocations_to_trajectory
  persist_text:
    text: draw_ecomap
```

Here's what using the task added in #89 would look like here, but #89 gives a fuller example in the tests.

2024-07-22 14:44 UTC, cisaacstern reviewed
This is awesome!!! 🤩 Thanks so much!

2024-07-22 14:44 UTC, cisaacstern approved these changes

2024-07-22 14:44 UTC, merged